# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd2101673d91e4fd6afdbbf877942c8e9234161b117dc06aa242105116d8e2534d82ac78f60b08145b70981b4062337814792e050a0eae7d3b08636c6f8799a7

test:
  secret_key_base: 56e50cca2b429a79ee9f2725105933a389f507e745bed425cdb6d10bdc0634893cbcad7f96290a178ec8be8b57de2d9abc2dc788bea447e546ab1fafdbb1a955

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
